version: '2.27.0'
services:
  flower_shop:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - flowers_db
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  flowers_db:
    restart: always
    image: postgres:alpine3.19
    environment:
      - POSTGRES_DB=cottonpads
      - POSTGRES_USER=daniilmolchanov
      - POSTGRES_PASSWORD=microcuts1928
    ports:
      - "5432:5432"




