version: '3'
services:
  flower_shop:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /root/var/lib/docker/volumes/flowers:/src/main/resources/flowers
    ports:
      - "8080:8080"
    depends_on:
      - flowers_db
  flowers_db:
    restart: always
    image: postgres:alpine3.19
    environment:
      - POSTGRES_DB=cottonpads
      - POSTGRES_USER=daniilmolchanov
      - POSTGRES_PASSWORD=microcuts1928
    ports:
      - "5432:5432"
volumes:
  - flowers:




