# Exported from Render on 2024-04-25T21:10:04Z
services:
- type: web
  name: flower_shop
  runtime: docker
  repo: https://github.com/DaniilMolchanov666/Flower-Shop
  plan: free
  region: oregon
  startCommand: docker-compose run
version: "1"
