spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/cottonpads
    username: daniilmolchanov
    password: microcuts1928
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
bot:
  name: Prozvetanie_Flower_Shop_bot
  token: 7091988555:AAHmFSmxmJKkyk8JB9cRAMfd0Z0YlIXo-uk
