spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-coh7u16d3nmc73a0ui6g-a.oregon-postgres.render.com:5432/cottonpads
    username: daniilmolchanov
    password: OOXhDQGFGZusuqnEAF4CkgeyUhvLmTyi
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
telegram:
  bot:
    name: Prozvetanie_Flower_Shop_bot
    token: 7091988555:AAHmFSmxmJKkyk8JB9cRAMfd0Z0YlIXo-uk
  webhook-path: localhost:8080

