spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://89.104.68.91:5432/cottonpads
    username: daniilmolchanov
    password: microcuts1928
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
telegram:
  bot:
    name: Procvetanie_Shop_Bot
    token: 6996412649:AAEjERQih6LGvG4R17oAqEvEKiZbtgMPXqA
port:
  9000

