spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-coh7u16d3nmc73a0ui6g-a:5450/cottonpads
    username: daniilmolchanov
    password: microcuts1928
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
telegram:
  bot:
    name: Prozvetanie_Flower_Shop_bot
    token: 7091988555:AAFcBvGAlF8A8piWjlFaL_OGXV0wLpxD4yk

